### ISSUE TITLE
Several compile errors during Android build, need more  #if EDITOR conditions

### ISSUE THREAD

**Issue by NeatWolf** [Thundernerd/Unity3D-IconManager#3]
Hi,

the class works just as fine until you build, then all of the classes methods and stuff of course begin throwing errors since there are parts of the code that can't work outside the editor.

I did a quick'n'dirty fix by just throwing a few #if EDITOR clauses here and there, but you may want to have something more tidy for that for the release version :)

**Comment by Thundernerd** [comment]
Ah yes, thanks for notifying me about this. I'll make sure it gets fixed in the new release!
